[package]
version = "0.12.2"
title = "railOmniverse Extension Demo Version"
description = "railOmniverse implements a 'trackjoint' for railing things."
authors = ["Trend Redaktions- und Verlagsgesellschaft mbH <horstmann.marc@trendverlag.de>"]
category = "simulation"
feature = false
app = false
repository="https://www.trendverlag.com"
readme  = "docs/README.md"
keywords = ["simulation", "physics", "rail", "track", "train"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/Thumbnail.jpg"
icon = "data/PhysXlogo.png"

[package.target]
config = ["release"]
kit = ["105.1.0"]

[package.writeTarget]
kit = true

[dependencies]
"omni.usd.schema.rail.core" = {}
"omni.physx.bundle" = {}

# extension deps below are required for the property widget code to work
"omni.kit.property.physx" = {}
"omni.kit.commands" = {}
"omni.usd" = {}
"omni.physx.ui" = {}

[[native.plugin]]
path = "bin/omni.rail.core.plugin"
recursive = false

[[python.module]]
name = "omni.rail.core"
